version: '3.4'
services:

  immudb:
    image: codenotary/immudb:latest
    ports:
      - "3322:3322" # The immutable database
      - "8080:8080" # The database admin web front end
      - "5432:5432" # The posrtgres compatible interface
    environment:
      IMMUDB_PGSQL_SERVER: 'true'

  # As an example we'll add login/registration to 
  # https://hub.docker.com/r/containous/whoami
  whoami:
    image: containous/whoami
    ports:
      - "32769:80"

  development:
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/vscode:cached
      # Give access to ssh keys on the host (Is there a better way to do this?)
      - ~/.ssh:/home/host-ssh:cached
      # We need this so docker in docker works (Check this)
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      DATABASE_URL: postgresql://immudb:immudb@immudb:5432/defaultdb?sslmode=disable
      MIGRATIONS_DATABASE_URL: postgresql://immudb:immudb@localhost:5432/defaultdb?sslmode=disable

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    working_dir: /vscode
    
    depends_on:
      - immudb
